name: elegant_spring_animation
description: A package that provides an intuitive API for using spring animations.
version: 2.0.1
#homepage:
repository: https://github.com/ercantomac/elegant_spring_animation
topics:
  - animation
  - spring

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
