name: elegant_spring_animation
description: A package that provides an intuitive API for using spring animations.
version: 1.0.0
#homepage:
repository:
topics:
  - animation

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
